import { Country } from "country-state-city";

const DEFAULT_INDUSTRIES = [
  "AI",
  "Advertising",
  "Blockchain",
  "Biotech",
  "Energy",
  "HRTech",
  "EdTech",
  "Fintech",
  "HealthTech",
  "LegalTech",
  "PropTech",
  "Apparel and Accessories",
  "Food and Beverage",
  "Furniture and Home Decor",
  "Health and Beauty",
  "Media and Entertainment",
  "Other",
];

export const defaultFounderForm = {
  display: "form",
  components: [
    {
      label: "Name",
      labelPosition: "top",
      placeholder: "Name",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      inputMask: "",
      displayMask: "",
      applyMaskOn: "change",
      allowMultipleMasks: false,
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      showWordCount: false,
      showCharCount: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: 3,
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "name",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "textfield",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      addons: [],
      inputType: "text",
      id: "euv6af8",
      defaultValue: "",
    },
    {
      label: "Email",
      labelPosition: "top",
      placeholder: "Email",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      displayMask: "",
      applyMaskOn: "change",
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: "",
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      kickbox: {
        enabled: false,
      },
      errorLabel: "",
      errors: "",
      key: "email",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "email",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      inputType: "email",
      inputMask: "",
      id: "eavqzk",
      defaultValue: "",
    },
    {
      label: "LinkedIn URL",
      labelPosition: "top",
      placeholder: "LinkedIn URL",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      displayMask: "",
      applyMaskOn: "change",
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: "",
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      kickbox: {
        enabled: false,
      },
      errorLabel: "",
      errors: "",
      key: "linkedinurl",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "url",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      inputType: "url",
      inputMask: "",
      id: "sdjfc",
      defaultValue: "",
    },
    {
      label: "Which country are you from?",
      labelPosition: "top",
      widget: "choicesjs",
      placeholder: "",
      description: "",
      tooltip: "",
      customClass: "",
      tabindex: "",
      hidden: false,
      hideLabel: false,
      uniqueOptions: false,
      autofocus: false,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      dataSrc: "values",
      data: {
        values: Country.getAllCountries().map((country) => ({
          label: country.name,
          value: country.isoCode,
        })),
        resource: "",
        url: "",
        json: "",
        custom: "",
      },
      dataType: "",
      idPath: "id",
      valueProperty: "",
      template: "<span>{{ item.label }}</span>",
      refreshOn: "",
      refreshOnBlur: "",
      clearOnRefresh: false,
      searchEnabled: true,
      selectThreshold: 0.3,
      readOnlyValue: false,
      customOptions: {},
      useExactSearch: false,
      persistent: true,
      protected: false,
      dbIndex: false,
      encrypted: false,
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        onlyAvailableItems: false,
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "country",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "select",
      indexeddb: {
        filter: {},
      },
      dataGridLabel: false,
      lazyLoad: true,
      selectFields: "",
      searchField: "",
      searchDebounce: 0.3,
      minSearch: 0,
      filter: "",
      limit: 100,
      authenticate: false,
      ignoreCache: false,
      redrawOn: "",
      input: true,
      prefix: "",
      suffix: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      fuseOptions: {
        include: "score",
        threshold: 0.3,
      },
      id: "ezc2qp",
      defaultValue: "",
    },
    {
      label: "What industry is your company in?",
      labelPosition: "top",
      widget: "choicesjs",
      placeholder: "",
      description: "",
      tooltip: "",
      customClass: "",
      tabindex: "",
      hidden: false,
      hideLabel: false,
      uniqueOptions: false,
      autofocus: false,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      dataSrc: "values",
      data: {
        values: DEFAULT_INDUSTRIES.map((industry) => ({
          label: industry,
          value: industry,
        })),
        resource: "",
        url: "",
        json: "",
        custom: "",
      },
      dataType: "",
      idPath: "id",
      valueProperty: "",
      template: "<span>{{ item.label }}</span>",
      refreshOn: "",
      refreshOnBlur: "",
      clearOnRefresh: false,
      searchEnabled: true,
      selectThreshold: 0.3,
      readOnlyValue: false,
      customOptions: {},
      useExactSearch: false,
      persistent: true,
      protected: false,
      dbIndex: false,
      encrypted: false,
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        onlyAvailableItems: false,
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "industry",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "select",
      indexeddb: {
        filter: {},
      },
      dataGridLabel: false,
      lazyLoad: true,
      selectFields: "",
      searchField: "",
      searchDebounce: 0.3,
      minSearch: 0,
      filter: "",
      limit: 100,
      authenticate: false,
      ignoreCache: false,
      redrawOn: "",
      input: true,
      prefix: "",
      suffix: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      fuseOptions: {
        include: "score",
        threshold: 0.3,
      },
      id: "e6iikqd",
      defaultValue: "",
    },
  ],
  /*
    {
      type: "button",
      label: "Submit",
      key: "submit",
      size: "md",
      block: false,
      action: "submit",
      disableOnInvalid: true,
      theme: "primary",
      id: "eztz1z7",
      input: true,
      placeholder: "",
      prefix: "",
      customClass: "",
      suffix: "",
      multiple: false,
      defaultValue: null,
      protected: false,
      unique: false,
      persistent: false,
      hidden: false,
      clearOnHide: true,
      refreshOn: "",
      redrawOn: "",
      tableView: false,
      modalEdit: false,
      dataGridLabel: true,
      labelPosition: "top",
      description: "",
      errorLabel: "",
      tooltip: "",
      hideLabel: false,
      tabindex: "",
      disabled: false,
      autofocus: false,
      dbIndex: false,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      widget: {
        type: "input",
      },
      attributes: {},
      validateOn: "change",
      validate: {
        required: false,
        custom: "",
        customPrivate: false,
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      conditional: {
        show: null,
        when: null,
        eq: "",
      },
      overlay: {
        style: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      allowCalculateOverride: false,
      encrypted: false,
      showCharCount: false,
      showWordCount: false,
      properties: {},
      allowMultipleMasks: false,
      addons: [],
      leftIcon: "",
      rightIcon: "",
    },
  ],*/
};

export const defaultInvestorForm = {
  display: "form",
  components: [
    {
      label: "Name",
      labelPosition: "top",
      placeholder: "Name",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      inputMask: "",
      displayMask: "",
      applyMaskOn: "change",
      allowMultipleMasks: false,
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      showWordCount: false,
      showCharCount: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: 3,
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "name",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "textfield",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      addons: [],
      inputType: "text",
      id: "euv6af8",
      defaultValue: "",
    },
    {
      label: "Email",
      labelPosition: "top",
      placeholder: "Email",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      displayMask: "",
      applyMaskOn: "change",
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: "",
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      kickbox: {
        enabled: false,
      },
      errorLabel: "",
      errors: "",
      key: "email",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "email",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      inputType: "email",
      inputMask: "",
      id: "eavqzk",
      defaultValue: "",
    },
    {
      label: "LinkedIn URL",
      labelPosition: "top",
      placeholder: "LinkedIn URL",
      description: "",
      tooltip: "",
      prefix: "",
      suffix: "",
      widget: {
        type: "input",
      },
      displayMask: "",
      applyMaskOn: "change",
      customClass: "",
      tabindex: "",
      autocomplete: "",
      hidden: false,
      hideLabel: false,
      mask: false,
      autofocus: false,
      spellcheck: true,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      persistent: true,
      inputFormat: "plain",
      protected: false,
      dbIndex: false,
      case: "",
      truncateMultipleSpaces: false,
      encrypted: false,
      redrawOn: "",
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        pattern: "",
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        minLength: "",
        maxLength: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      kickbox: {
        enabled: false,
      },
      errorLabel: "",
      errors: "",
      key: "linkedinurl",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "url",
      dataGridLabel: false,
      input: true,
      refreshOn: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      inputType: "url",
      inputMask: "",
      id: "sdjfc",
      defaultValue: "",
    },
    {
      label: "Which country are you from?",
      labelPosition: "top",
      widget: "choicesjs",
      placeholder: "",
      description: "",
      tooltip: "",
      customClass: "",
      tabindex: "",
      hidden: false,
      hideLabel: false,
      uniqueOptions: false,
      autofocus: false,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      dataSrc: "values",
      data: {
        values: Country.getAllCountries().map((country) => ({
          label: country.name,
          value: country.isoCode,
        })),
        resource: "",
        url: "",
        json: "",
        custom: "",
      },
      dataType: "",
      idPath: "id",
      valueProperty: "",
      template: "<span>{{ item.label }}</span>",
      refreshOn: "",
      refreshOnBlur: "",
      clearOnRefresh: false,
      searchEnabled: true,
      selectThreshold: 0.3,
      readOnlyValue: false,
      customOptions: {},
      useExactSearch: false,
      persistent: true,
      protected: false,
      dbIndex: false,
      encrypted: false,
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        onlyAvailableItems: false,
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "country",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "select",
      indexeddb: {
        filter: {},
      },
      dataGridLabel: false,
      lazyLoad: true,
      selectFields: "",
      searchField: "",
      searchDebounce: 0.3,
      minSearch: 0,
      filter: "",
      limit: 100,
      authenticate: false,
      ignoreCache: false,
      redrawOn: "",
      input: true,
      prefix: "",
      suffix: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      fuseOptions: {
        include: "score",
        threshold: 0.3,
      },
      id: "ezc2qp",
      defaultValue: "",
    },
    {
      label: "Which industries are you interested in investing in?",
      labelPosition: "top",
      widget: "choicesjs",
      placeholder: "",
      description: "",
      tooltip: "",
      customClass: "",
      tabindex: "",
      hidden: false,
      hideLabel: false,
      uniqueOptions: false,
      autofocus: false,
      disabled: false,
      tableView: true,
      modalEdit: false,
      multiple: false,
      dataSrc: "values",
      values: DEFAULT_INDUSTRIES.map((industry) => ({
        label: industry,
        value: industry,
      })),
      dataType: "",
      idPath: "id",
      valueProperty: "",
      template: "<span>{{ item.label }}</span>",
      refreshOn: "",
      refreshOnBlur: "",
      clearOnRefresh: false,
      searchEnabled: true,
      selectThreshold: 0.3,
      readOnlyValue: false,
      customOptions: {},
      useExactSearch: false,
      persistent: true,
      protected: false,
      dbIndex: false,
      encrypted: false,
      clearOnHide: true,
      customDefaultValue: "",
      calculateValue: "",
      calculateServer: false,
      allowCalculateOverride: false,
      validateOn: "change",
      validate: {
        required: true,
        onlyAvailableItems: false,
        customMessage: "",
        custom: "",
        customPrivate: false,
        json: "",
        strictDateValidation: false,
        multiple: false,
        unique: false,
      },
      unique: false,
      validateWhenHidden: false,
      errorLabel: "",
      errors: "",
      key: "industry",
      tags: [],
      properties: {},
      conditional: {
        show: null,
        when: null,
        eq: "",
        json: "",
      },
      customConditional: "",
      logic: [],
      attributes: {},
      overlay: {
        style: "",
        page: "",
        left: "",
        top: "",
        width: "",
        height: "",
      },
      type: "selectboxes",
      indexeddb: {
        filter: {},
      },
      dataGridLabel: false,
      lazyLoad: true,
      selectFields: "",
      searchField: "",
      searchDebounce: 0.3,
      minSearch: 0,
      filter: "",
      limit: 100,
      authenticate: false,
      ignoreCache: false,
      redrawOn: "",
      input: true,
      prefix: "",
      suffix: "",
      showCharCount: false,
      showWordCount: false,
      allowMultipleMasks: false,
      addons: [],
      fuseOptions: {
        include: "score",
        threshold: 0.3,
      },
      id: "e6iikqd",
      defaultValue: "",
    },
  ],
};
